config/routes.rb
Moto1Server::Application.routes.draw do
  resources :users

  resources :operators

  resources :call_for_helps

  match '/user/authenticate' => 'users#authenticate'

end

app/models/call_for_help.rb
class CallForHelp < ActiveRecord::Base
  attr_accessible :name, :problem, :lng, :lat
end

app/models/operator.rb
class Operator < ActiveRecord::Base
  attr_accessible :logedin, :operator, :phone
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :active, :email, :firstname, :key, :lastname, :password, :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/call_for_helps_controller.rb
class CallForHelpsController < ApplicationController
  # GET /call_for_helps
  # GET /call_for_helps.json
  def index
    @call_for_helps = CallForHelp.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @call_for_helps }
    end
  end

  # GET /call_for_helps/1
  # GET /call_for_helps/1.json
  def show
    @call_for_help = CallForHelp.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @call_for_help }
    end
  end

  # GET /call_for_helps/new
  # GET /call_for_helps/new.json
  def new
    @call_for_help = CallForHelp.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @call_for_help }
    end
  end

  # GET /call_for_helps/1/edit
  def edit
    @call_for_help = CallForHelp.find(params[:id])
  end

  # POST /call_for_helps
  # POST /call_for_helps.json
  def create
    @call_for_help = CallForHelp.new(params[:call_for_help])

    respond_to do |format|
      if @call_for_help.save
        # Send SMS message
        send_sms()
        #
        format.html { redirect_to @call_for_help, notice: 'Call for help was successfully created.' }
        format.json { render json: @call_for_help, status: :created, location: @call_for_help, message: 'Call for help was successfully created.' }
      else
        format.html { render action: "new" }
        format.json { render json: @call_for_help.errors, status: :unprocessable_entity }
      end
    end
  end

  def send_sms
    Rails.logger.info("Connecting to SMS service...")
    message = 'User %s is having %s problem @%0.6f, %0.6f. See details http://ec2-54-235-172-210.compute-1.amazonaws.com:3029/call_for_helps/%i' % [@call_for_help.name, @call_for_help.problem, @call_for_help.lng, @call_for_help.lat, @call_for_help.id]
    api = Clickatell::API.authenticate('3451859', 'jordan.vrtanoski.tsba', 'TsBa123123')
    @all_operators=Operator.find_all_by_logedin(true)
    @all_operators.each do |operator|
#      message_id = api.send_message(operator.phone, message, :from => '+971559342320')
      message_id = api.send_message(operator.phone, message)
      Rails.logger.info("Message sent to %s on %s with message_id %s" % [operator.operator, operator.phone, message_id])
    end
  end

  # PUT /call_for_helps/1
  # PUT /call_for_helps/1.json
  def update
    @call_for_help = CallForHelp.find(params[:id])

    respond_to do |format|
      if @call_for_help.update_attributes(params[:call_for_help])
        format.html { redirect_to @call_for_help, notice: 'Call for help was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @call_for_help.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /call_for_helps/1
  # DELETE /call_for_helps/1.json
  def destroy
    @call_for_help = CallForHelp.find(params[:id])
    @call_for_help.destroy

    respond_to do |format|
      format.html { redirect_to call_for_helps_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/operators_controller.rb
class OperatorsController < ApplicationController
  # GET /operators
  # GET /operators.json
  def index
    @operators = Operator.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @operators }
    end
  end

  # GET /operators/1
  # GET /operators/1.json
  def show
    @operator = Operator.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @operator }
    end
  end

  # GET /operators/new
  # GET /operators/new.json
  def new
    @operator = Operator.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @operator }
    end
  end

  # GET /operators/1/edit
  def edit
    @operator = Operator.find(params[:id])
  end

  # POST /operators
  # POST /operators.json
  def create
    @operator = Operator.new(params[:operator])

    respond_to do |format|
      if @operator.save
        format.html { redirect_to @operator, notice: 'Operator was successfully created.' }
        format.json { render json: @operator, status: :created, location: @operator }
      else
        format.html { render action: "new" }
        format.json { render json: @operator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /operators/1
  # PUT /operators/1.json
  def update
    @operator = Operator.find(params[:id])

    respond_to do |format|
      if @operator.update_attributes(params[:operator])
        format.html { redirect_to @operator, notice: 'Operator was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @operator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operators/1
  # DELETE /operators/1.json
  def destroy
    @operator = Operator.find(params[:id])
    @operator.destroy

    respond_to do |format|
      format.html { redirect_to operators_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end


  # GET /users/authenticate.json
  def authenticate
    @user = User.find_by_username(params[:username])

    Rails.logger.info("User search finished")
    respond_to do |format|
      if ! @user.nil?
        Rails.logger.info("User found")
        if @user.active?
          Rails.logger.info("User active")
          if @user.password == params[:password]
            Rails.logger.info("Password is fine")
            format.json { render json: @user }
          else
            Rails.logger.info("Password is wrong")
          end
        else
          Rails.logger.info("User is not active")
        end
      end
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/call_for_helps_helper.rb
module CallForHelpsHelper
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/call_for_helps/_form.html.erb
<%= form_for(@call_for_help) do |f| %>
  <% if @call_for_help.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@call_for_help.errors.count, "error") %> prohibited this call_for_help from being saved:</h2>

      <ul>
      <% @call_for_help.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :problem %>
    <%= f.text_field :problem %>

    <%= f.label :lat %>
    <%= f.text_field :lat %>

    <%= f.label :lng %>
    <%= f.text_field :lng %>

    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/call_for_helps/edit.html.erb
<h1>Editing call_for_help</h1>

<%= render 'form' %>

<%= link_to 'Show', @call_for_help %> |
<%= link_to 'Back', call_for_helps_path %>

app/views/call_for_helps/index.html.erb
<h1>Listing call_for_helps</h1>

<table>
  <tr>
    <th>User Name</th>
    <th>Longitude</th>
    <th>Latitude</th>
    <th>Type of problem</th>
  </tr>

<% @call_for_helps.each do |call_for_help| %>
  <tr>
    <td><%= call_for_help.name %></td>
    <td><%= call_for_help.lng %></td>
    <td><%= call_for_help.lat %></td>
    <td><%= call_for_help.problem %></td>

    <td><%= link_to 'Show', call_for_help %></td>
    <td><%= link_to 'Edit', edit_call_for_help_path(call_for_help) %></td>
    <td><%= link_to 'Destroy', call_for_help, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Call for help', new_call_for_help_path %>

app/views/call_for_helps/new.html.erb
<h1>New call_for_help</h1>

<%= render 'form' %>

<%= link_to 'Back', call_for_helps_path %>

app/views/call_for_helps/show.html.erb
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
<script>
    function initialize() {
        var myLatlng = new google.maps.LatLng(<%= @call_for_help.lat %>,<%= @call_for_help.lng %>);
        var mapOptions = {
            zoom: 12,
            center: myLatlng,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

        var marker = new google.maps.Marker({
            position: myLatlng,
            map: map,
            title: '<%= @call_for_help.name %> is having <%= @call_for_help.problem %> problem.'
        });
    }

    google.maps.event.addDomListener(window, 'load', initialize);

</script>

<p id="notice"><%= notice %></p>

<table>
<tr>
  <td>
    <b>Name</b>
  </td>
  <td><%= @call_for_help.name %></td>
</tr>
<tr>
  <td>
    <b>Longitude</b>
  </td>
  <td><%= @call_for_help.lng %></td>
</tr>
<tr>
  <td>
    <b>Latitude</b>
  </td>
  <td><%= @call_for_help.lat %></td>
</tr>
<tr>
  <td>
    <b>Type of problem</b>
  </td>
  <td><%= @call_for_help.problem %></td>
</tr>
</table>

<div id="map-canvas" style="height:400px;width:400px"></div>

<%= link_to 'Edit', edit_call_for_help_path(@call_for_help) %> |
<%= link_to 'Back', call_for_helps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moto1Server</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/operators/_form.html.erb
<%= form_for(@operator) do |f| %>
  <% if @operator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operator.errors.count, "error") %> prohibited this operator from being saved:</h2>

      <ul>
      <% @operator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :operator %><br />
    <%= f.text_field :operator %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :logedin %><br />
    <%= f.check_box :logedin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/operators/edit.html.erb
<h1>Editing operator</h1>

<%= render 'form' %>

<%= link_to 'Show', @operator %> |
<%= link_to 'Back', operators_path %>

app/views/operators/index.html.erb
<h1>Listing operators</h1>

<table>
  <tr>
    <th>Operator</th>
    <th>Phone</th>
    <th>Logedin</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @operators.each do |operator| %>
  <tr>
    <td><%= operator.operator %></td>
    <td><%= operator.phone %></td>
    <td><%= operator.logedin %></td>
    <td><%= link_to 'Show', operator %></td>
    <td><%= link_to 'Edit', edit_operator_path(operator) %></td>
    <td><%= link_to 'Destroy', operator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Operator', new_operator_path %>

app/views/operators/new.html.erb
<h1>New operator</h1>

<%= render 'form' %>

<%= link_to 'Back', operators_path %>

app/views/operators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Operator:</b>
  <%= @operator.operator %>
</p>

<p>
  <b>Phone:</b>
  <%= @operator.phone %>
</p>

<p>
  <b>Logedin:</b>
  <%= @operator.logedin %>
</p>


<%= link_to 'Edit', edit_operator_path(@operator) %> |
<%= link_to 'Back', operators_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :key %><br />
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Email</th>
    <th>Password</th>
    <th>Key</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.firstname %></td>
    <td><%= user.lastname %></td>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= user.key %></td>
    <td><%= user.active %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Firstname:</b>
  <%= @user.firstname %>
</p>

<p>
  <b>Lastname:</b>
  <%= @user.lastname %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Key:</b>
  <%= @user.key %>
</p>

<p>
  <b>Active:</b>
  <%= @user.active %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>